
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 43;
  public static final int SEQ = 19;
  public static final int DIVIDE = 16;
  public static final int OCURLYBRACKET = 56;
  public static final int CHAR = 3;
  public static final int CONCATENATE = 22;
  public static final int INTEGER = 35;
  public static final int NOTEQUAL = 28;
  public static final int INT = 8;
  public static final int ENDDO = 48;
  public static final int LESS = 23;
  public static final int MINUS = 14;
  public static final int CHARACTER = 33;
  public static final int OBRACKET = 52;
  public static final int SEMICOLON = 60;
  public static final int NOT = 5;
  public static final int AND = 6;
  public static final int ELSEIF = 46;
  public static final int RATIONAL = 37;
  public static final int CBRACKET = 53;
  public static final int IN = 20;
  public static final int OR = 7;
  public static final int TDEF = 29;
  public static final int COMMA = 58;
  public static final int BOOL = 4;
  public static final int RAT = 10;
  public static final int MOREEQ = 26;
  public static final int PLUS = 13;
  public static final int IF = 40;
  public static final int LESSEQ = 24;
  public static final int MAIN = 2;
  public static final int DOT = 39;
  public static final int BOOLEAN_CONSTANT = 34;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 49;
  public static final int OSQUAREBRACKET = 54;
  public static final int ASS = 38;
  public static final int EQUAL = 27;
  public static final int error = 1;
  public static final int FDEF = 30;
  public static final int VOID = 61;
  public static final int CCURLYBRACKET = 57;
  public static final int TOP = 11;
  public static final int TIMES = 15;
  public static final int COLON = 59;
  public static final int ENDIF = 45;
  public static final int ELSE = 41;
  public static final int DICT = 18;
  public static final int READ = 50;
  public static final int CSQUAREBRACKET = 55;
  public static final int WHILE = 42;
  public static final int FLOAT = 9;
  public static final int THEN = 44;
  public static final int LEN = 21;
  public static final int STRING = 12;
  public static final int ALIAS = 31;
  public static final int FLOATING_POINT = 36;
  public static final int PRINT = 51;
  public static final int DO = 47;
  public static final int MORE = 25;
  public static final int EXPONENT = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "CHAR",
  "BOOL",
  "NOT",
  "AND",
  "OR",
  "INT",
  "FLOAT",
  "RAT",
  "TOP",
  "STRING",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "EXPONENT",
  "DICT",
  "SEQ",
  "IN",
  "LEN",
  "CONCATENATE",
  "LESS",
  "LESSEQ",
  "MORE",
  "MOREEQ",
  "EQUAL",
  "NOTEQUAL",
  "TDEF",
  "FDEF",
  "ALIAS",
  "ID",
  "CHARACTER",
  "BOOLEAN_CONSTANT",
  "INTEGER",
  "FLOATING_POINT",
  "RATIONAL",
  "ASS",
  "DOT",
  "IF",
  "ELSE",
  "WHILE",
  "FORALL",
  "THEN",
  "ENDIF",
  "ELSEIF",
  "DO",
  "ENDDO",
  "RETURN",
  "READ",
  "PRINT",
  "OBRACKET",
  "CBRACKET",
  "OSQUAREBRACKET",
  "CSQUAREBRACKET",
  "OCURLYBRACKET",
  "CCURLYBRACKET",
  "COMMA",
  "COLON",
  "SEMICOLON",
  "VOID"
  };
}

